### PR TITLE
feat: audit-config support for organizations

### PR DESCRIPTION
**Pull request by ekremney**
Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Review by iuliag — COMMENTED** [review]
Should it be merged into config, just like it's mentioned for the audit config and config of sites in the data model?
Also, at the workshop, feedback was `auditDisabled: false` (as exposed in the API) is not user friendly, compared to `auditsEnabled: true`.

**Comment by ekremney** [comment]
@iuliag as far as I understand `config` and `auditConfig` are separate things: https://lucid.app/lucidchart/f5480d07-626d-42e8-8eb5-39b0e9a1c75f/edit?page=0_0

**Comment by alinarublea** [comment]
Yes, right now auditConfig and config are separate but the plan is to merge them and auditConfig be a part of config. Not sure how urgent it is to merge them.

**Review by alinarublea — APPROVED** [review]
Looks good to me,I would also add an IT test

**Pull request merged**
